### ISSUE TITLE
Kursfeedback ht20

### ISSUE THREAD

**Issue by AuroraBTH** [dbwebb-se/design-v3#5]
Då förbereder vi oss för att samla in kursfeedback för hösten 2020.

# Labbmiljö

[Bra att ha länkar](https://gist.github.com/AuroraBTH/d067b9605b832470a6eb7ce536265f7c)

# Kmom01

- [ ] Fundering: Kör normal standard i SASS - 2 spaces
- [ ] Fundering: Lägg till video om hur man kan jobba med Git
- [ ] Fundering: Videointroduktionen till Pico är med gamla sidan, kanske behöver uppdateras

# Kmom02

- [ ] Fundering: `dbwebb validate` ska köra `npm run lint` i `me/portfolio`
- [ ] Fundering: Stäng av `dbwebb validate`
- [ ] Fundering: Lägg till krav och material om line-height, font-size, letter-spacing

# Kmom03

- [ ] Fundering: Nämn position, polyfill, sticky footer
- [ ] Fundering: Uppdatera Grid-guiden med tydligare exempel och mer om `fr` 

# Kmom04

- [ ] Fundering: Peer-to-peer feedback på analyserna
- [ ] Fundering: Artikel om färgblindhet, color wheel och gradient
- [ ] Uppdatering: Förtydliga hur mycket som skall skrivas i analyserna (04/05/06/10), eventuellt exempelanalys
- [ ] Uppdatering: Video som jobbar med färghjul och väljer ut färger att jobba med

# Kmom05

- [ ] Fundering: Förklara och motivera valet av cimage ytterligare

# Kmom06

- [ ] Fundering: Nämn lagen om tillgänglighet i offentlig service i Sverige (2019) + tillgänglighetsdirektivet för mobila applikationer (23 juni 2021)

# kmom10

- [ ] Fundering: Gemensam sida där alla studenter kan se varandras sidor
- [ ] Fundering: Alternativt tema för enkelt. Kanske byta till att göra en wireframe och implementerar den. Introducera material för hur man gör det i tidigare kursmoment

**Comment by mathiilda** [comment]
"Något att tänka på är att ge en tydligare förklaring över vad en flash-bild är, i och med att det var med i kraven för projektet. Söker man på flash-bild får man främst upp bilder på the Flash. Det var någon som redde ut det i chatten, men kan vara bra att förtydliga vad ni menar!"

**Comment by IdasLam** [comment]
Feedback
### Kmom10

"Då vi skriver många analyser både under kursens gång samt två stycken för projektet hade jag uppskattat lite mer vägledning för dessa, kanske något extra läsmaterial eller om man kan få någon typ av feedback på dem vid rättning av kursmomenten, för att säkerställa att man skriver på rätt sätt."
